name: markdown-lint
permissions:
  contents: read
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25
        with:
          fix: true
          globs: |
            *.md
            !src/**/*.md
            !test/**/*.md
