name: markdown-lint
permissions:
  contents: read
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe
        with:
          fix: true
          globs: |
            *.md
            !src/**/*.md
            !test/**/*.md
