name: "DevContainer Features - Release"
permissions:
  contents: write
  packages: write
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  run-tests:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_tests == true || github.event_name == 'push' }}
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  deploy:
    needs: [run-tests]
    if: needs.run-tests.result == 'success' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Publish Features
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
