name: "DevContainer Features - Release"
permissions:
  contents: write
  packages: write
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  run-tests:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  deploy:
    needs: [run-tests]
    if: needs.run-tests.result == 'success' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Publish Features
        uses: devcontainers/action@bef2cf2d1a019b00b45e184f83035e01bd1972f3
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
