name: "PR - Test Updated Features"
permissions:
  contents: read
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ["pre-commit", "sonarlint", "uv"]
        baseImage: ["ubuntu:focal", "ubuntu:jammy", "debian:11", "debian:12", "mcr.microsoft.com/devcontainers/base:ubuntu", "mcr.microsoft.com/devcontainers/base:debian", "mcr.microsoft.com/devcontainers/base:noble"]
    steps:
      - uses: actions/checkout@v7
      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli
      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test  --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .
  test-scenarios:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ["pre-commit", "sonarlint", "uv"]
    steps:
      - uses: actions/checkout@v7
      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli
      - name: "Testing '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated  .
