name: "DevContainer Features - Test"
on:
  workflow_dispatch:
    inputs:
      on_changes_only:
        type: boolean
        description: "on_changes_only"
        default: false

      enabled:
        type: boolean
        description: "enabled"
        default: true

  workflow_call:
    inputs:
      on_changes_only:
        type: boolean
        description: "on_changes_only"
        default: false

      enabled:
        type: boolean
        description: "enabled"
        default: true

  schedule:
    # every day at 01:00
    - cron: "0 1 * * *"

  pull_request:

  push:
    branches:
      - master

jobs:
  test-scenarios:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ["pre-commit"]
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated  .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
